import type { SiteData } from "./types";

export const SITE_DATA: SiteData = {
  brand: {
    name: "성동교회",
    eng: "SUNGDONG CHURCH",
    tagline: "은혜와 진리가 흐르는 공동체",
    address: "서울특별시 성동구 왕십리로 123 성동교회",
    phone: "02-1234-5678",
    email: "hello@sungdongchurch.kr",
    representative: "대표 김주은 목사",
    businessNo: "123-45-67890",
    logoUrl: null,
  },
  nav: [
    { id: "about", label: "교회 소개", href: "/about", children: ["담임목사 인사", "교회 연혁", "비전과 사명"] },
    { id: "worship", label: "예배 안내", href: "/worship", children: ["주일예배", "수요예배", "새벽기도회"] },
    { id: "sermons", label: "말씀", href: "/sermons", children: ["설교 영상", "주보 다운로드", "큐티"] },
    { id: "notices", label: "교회 소식", href: "/notices", children: ["공지사항", "행사 캘린더"] },
    { id: "schedule", label: "일정", href: "/schedule" },
    // { id: "departments", label: "교회학교", href: "/departments" },
    { id: "gallery", label: "갤러리", href: "/gallery" },
    { id: "directions", label: "찾아오시는 길", href: "/directions" },
  ],
  hero: {
    feature: {
      tag: "오늘의 소식",
      title: "2026 부활주일 연합예배에 여러분을 초대합니다",
      desc: "온 성도가 한 자리에 모여 부활하신 주님을 함께 찬양합니다. 4월 5일 오전 11시, 본당.",
      meta: "MAR 28, 2026 · 담임 김주은 목사",
    },
    sideList: [
      { day: "27", mon: "MAR", title: "새가족 환영주일 — 첫 주일을 함께", cat: "공지" },
      { day: "24", mon: "MAR", title: "성경통독 365 — 봄학기 등록 안내", cat: "프로그램" },
      { day: "20", mon: "MAR", title: "고난주간 특별새벽기도회", cat: "예배" },
      { day: "15", mon: "MAR", title: "청년부 단기선교 보고회", cat: "선교" },
      { day: "10", mon: "MAR", title: "교회학교 봄 수련회 신청", cat: "교회학교" },
    ],
  },
  worshipServices: [
    { tag: "WEEK", name: "주일 1부 예배", time: "오전 09:00", meta: "본당 · 1시간 30분" },
    { tag: "WEEK", name: "주일 2부 예배", time: "오전 11:00", meta: "본당 · 1시간 30분", feat: true },
    { tag: "WEEK", name: "주일 3부 예배", time: "오후 02:00", meta: "본당 · 청년 중심" },
    { tag: "WEEK", name: "수요예배", time: "오후 07:30", meta: "본당 · 1시간" },
    { tag: "WEEK", name: "금요철야", time: "오후 09:00", meta: "본당 · 2시간" },
    { tag: "DAILY", name: "새벽기도회", time: "오전 05:30", meta: "본당 · 매일" },
  ],
  worshipOrder: [
    ["01", "예배의 부름", "사회자"],
    ["02", "기원 및 사도신경", "다 함 께"],
    ["03", "찬송", "다 함 께"],
    ["04", "대표 기도", "장로 / 권사"],
    ["05", "성경 봉독", "사회자"],
    ["06", "찬양", "성가대"],
    ["07", "설 교", "담임목사"],
    ["08", "찬송 및 봉헌", "다 함 께"],
    ["09", "축 도", "담임목사"],
  ],
  sermons: [
    { series: "마태복음 강해", title: "산상수훈, 천국 백성의 길", pastor: "김주은 목사", date: "2026.03.22", duration: "42:18", grad: "ph-grad-3" },
    { series: "주일설교", title: "흔들리지 않는 믿음", pastor: "김주은 목사", date: "2026.03.15", duration: "38:20", grad: "ph-grad-1" },
    { series: "수요예배", title: "기도의 골방으로", pastor: "이은혜 목사", date: "2026.03.18", duration: "32:45", grad: "ph-grad-2" },
    { series: "주일설교", title: "광야를 지나는 자에게", pastor: "김주은 목사", date: "2026.03.08", duration: "40:12", grad: "ph-grad-4" },
    { series: "특별집회", title: "부활의 능력 안에서", pastor: "박요한 목사", date: "2026.03.01", duration: "55:30", grad: "ph-grad-3" },
    { series: "수요예배", title: "선한 목자 되시는 주", pastor: "이은혜 목사", date: "2026.02.25", duration: "29:08", grad: "ph-grad-2" },
  ],
  sermonFilters: ["전체", "주일설교", "수요예배", "특별집회", "마태복음 강해"],
  departments: [
    { tag: "유아부", name: "꿈꾸는동산", age: "0–4세", leader: "최지민 전도사", count: 38 },
    { tag: "유치부", name: "샛별 유치부", age: "5–7세", leader: "한소영 전도사", count: 52 },
    { tag: "초등부", name: "꿈터 초등부", age: "초 1–6", leader: "정태훈 목사", count: 86 },
    { tag: "중등부", name: "비전 중등부", age: "중 1–3", leader: "김도현 목사", count: 64 },
    { tag: "고등부", name: "은혜 고등부", age: "고 1–3", leader: "이수진 목사", count: 47 },
    { tag: "청년부", name: "씨드(SEED)", age: "20–35세", leader: "박요한 목사", count: 124 },
  ],
  smallGroups: [
    { name: "기쁨셀", count: 12, meta: "수요일 저녁" },
    { name: "사랑셀", count: 8, meta: "금요일 저녁" },
    { name: "평강셀", count: 14, meta: "토요일 오전" },
    { name: "은혜셀", count: 10, meta: "주일 오후" },
    { name: "감사셀", count: 9, meta: "월요일 저녁" },
    { name: "소망셀", count: 11, meta: "화요일 저녁" },
    { name: "충성셀", count: 13, meta: "수요일 오전" },
    { name: "온유셀", count: 7, meta: "목요일 저녁" },
  ],
  notices: [
    { num: "142", cat: "공지", title: "[공지] 2026년 상반기 새가족반 등록 안내", author: "교무팀", date: "2026.03.25", pinned: true },
    { num: "141", cat: "행사", title: "[행사] 부활주일 연합예배 및 부활절 칸타타", author: "예배팀", date: "2026.03.22" },
    { num: "140", cat: "프로그램", title: "[프로그램] 성경통독 365 봄학기 모집", author: "교육팀", date: "2026.03.20" },
    { num: "139", cat: "교육", title: "[교육] 제자훈련 9기 모집 — 4월 개강", author: "양육팀", date: "2026.03.18" },
    { num: "138", cat: "공지", title: "[공지] 주차장 보수 공사로 인한 안내 (3/30 - 4/2)", author: "관리팀", date: "2026.03.16" },
    { num: "137", cat: "선교", title: "[선교] 캄보디아 단기선교팀 모집 (7/14-7/22)", author: "선교팀", date: "2026.03.14" },
    { num: "136", cat: "행사", title: "[행사] 부서별 봄 야유회 일정 모음", author: "교회학교", date: "2026.03.10" },
    { num: "135", cat: "공지", title: "[공지] 본당 음향 시스템 업그레이드 완료 안내", author: "관리팀", date: "2026.03.06" },
  ],
  noticeCategories: ["전체", "공지", "행사", "교육", "프로그램", "선교"],
  events: [
    { date: "APR 05", title: "부활주일 연합예배", meta: "오전 11:00 · 본당" },
    { date: "APR 12", title: "새가족 환영의 밤", meta: "오후 07:00 · 친교실" },
    { date: "APR 19", title: "전교인 가족 야유회", meta: "오전 09:00 · 양평 캠핑장" },
    { date: "APR 26", title: "제자훈련 9기 개강예배", meta: "오후 02:00 · 교육관 3층" },
  ],
  galleries: [
    { title: "2026 신년 감사예배", date: "JAN 01", grad: "ph-grad-1" },
    { title: "성가대 신년 발표회", date: "JAN 14", grad: "ph-grad-2" },
    { title: "청년부 동계 수련회", date: "JAN 27", grad: "ph-grad-3" },
    { title: "교회학교 추수감사절", date: "FEB 04", grad: "ph-grad-4" },
    { title: "선교 후원의 밤", date: "FEB 18", grad: "ph-grad-1" },
    { title: "고등부 졸업감사예배", date: "FEB 25", grad: "ph-grad-2" },
    { title: "사순절 특별 새벽기도", date: "MAR 06", grad: "ph-grad-3" },
    { title: "꿈터 초등부 봄소풍", date: "MAR 16", grad: "ph-grad-4" },
  ],
  galleryCategories: ["전체", "예배", "교회학교", "행사", "선교", "수련회"],
  bibleToday: {
    day: 87,
    title: "마태복음 5–7장 · 산상수훈",
    passages: ["마 5:1–12", "마 5:13–16", "마 5:17–48", "마 6:1–18", "마 7:1–14"],
    progress: 24,
    streak: 12,
    totalDays: 365,
  },
  qt: [
    { step: "STEP 01 · 본문", q: "오늘 본문에서 가장 마음에 와닿은 한 구절은 무엇입니까?" },
    { step: "STEP 02 · 묵상", q: "이 말씀이 나의 어떤 모습을 비추고 있습니까?" },
    { step: "STEP 03 · 적용", q: "오늘 하루, 어떻게 이 말씀을 살아낼 수 있을까요?" },
    { step: "STEP 04 · 기도", q: "이 말씀을 따라 살기 위해 무엇을 위해 기도하시겠습니까?" },
  ],
  pastor: {
    name: "김 주 은",
    role: "담임목사",
    eng: "KIM JU-EUN",
    message: `성동교회 홈페이지를 찾아주신 모든 분들을 진심으로 환영합니다. 우리 교회는 말씀과 기도, 그리고 사랑의 교제 위에 세워진 공동체입니다.

예수 그리스도 안에서 매일 새로워지는 삶, 이웃과 함께 나누는 삶을 추구합니다. 처음 오신 분도, 오랫동안 신앙 생활하신 분도 이곳에서 따뜻한 환대와 깊은 영적 성장을 경험하시기를 바랍니다.`,
    longMessage: `성동교회를 찾아주신 모든 분들을 진심으로 환영합니다. 우리 교회는 말씀과 기도, 사랑의 교제 위에 세워진 공동체입니다.

예수 그리스도 안에서 매일 새로워지는 삶, 이웃과 함께 나누는 삶을 추구합니다. 처음 오신 분에게는 따뜻한 환대를, 신앙 생활을 오래 해 오신 분에게는 깊은 영적 성장을 약속드립니다.

세상이 빠르게 변할수록 변치 않는 진리가 필요합니다. 성동교회가 그 진리 위에 든든히 서 있는 영적 안식처가 되기를 소망합니다.`,
  },
  vision: [
    { ko: "예배하는", en: "WORSHIP", desc: "온 마음으로 하나님께 드리는 예배. 우리 신앙의 가장 중심에 있는 것은 예배입니다." },
    { ko: "양육하는", en: "DISCIPLE", desc: "말씀과 기도로 자라가는 제자. 한 사람을 깊이, 그리고 끝까지 양육합니다." },
    { ko: "흘러가는", en: "MISSION", desc: "이웃과 열방을 향해 흘러가는 사랑. 받은 은혜를 세상으로 흘려보냅니다." },
  ],
  history: [
    { y: "1979", t: "성동교회 설립", d: "성동구 마장동 가정집에서 12명의 성도와 함께 첫 예배를 드리다." },
    { y: "1987", t: "본당 봉헌", d: "왕십리로 현 위치에 본당을 봉헌하며 새로운 부흥의 장을 열다." },
    { y: "1998", t: "교육관 신축", d: "다음 세대를 위한 교육관을 신축, 교회학교 6개 부서로 확장." },
    { y: "2010", t: "선교 동역 시작", d: "캄보디아 · 몽골 · 베트남 3개국 선교사 파송 시작." },
    { y: "2018", t: "성도 1,200명", d: "주일 출석 성도 1,200명을 넘어서며 다음 단계의 비전을 준비." },
    { y: "2024", t: "리뉴얼 헌당", d: "본당 리뉴얼을 통해 다음 세대와 함께 걸어갈 새 그릇을 세우다." },
  ],
  staff: [
    { name: "김주은", role: "담임목사", area: "전체 사역" },
    { name: "이은혜", role: "부목사", area: "예배 · 행정" },
    { name: "박요한", role: "청년부 담당", area: "씨드 청년부" },
    { name: "정태훈", role: "교육 담당", area: "초등부" },
    { name: "이수진", role: "교육 담당", area: "고등부" },
    { name: "김도현", role: "교육 담당", area: "중등부" },
    { name: "한소영", role: "전도사", area: "유치부" },
    { name: "최지민", role: "전도사", area: "유아부" },
  ],
  prayerSamples: [
    { who: "ㅇㅎㅈ 자매", topic: "딸의 대학 진학과 진로를 위해 기도해주세요." },
    { who: "익명", topic: "오랜 시간 멀어졌던 가족과의 화해를 위해 기도 부탁드립니다." },
    { who: "ㄱㅈㅎ 형제", topic: "수술을 앞두고 있습니다. 평안과 회복을 구합니다." },
    { who: "선교사 가정", topic: "캄보디아 현지 사역과 자녀 교육을 위해 기도해주세요." },
  ],
  prayerCategories: ["가정 / 자녀", "건강 / 치유", "직장 / 진로", "신앙 성장", "관계 / 화해", "기타"],
  prayerScopes: ["중보기도팀에게만", "담임목사에게만", "전체 성도와 함께"],
  transportation: [
    { tag: "지하철", icon: "🚇", title: "왕십리역 5번 출구", desc: "도보 7분 · 2호선 / 5호선 / 분당선 / 경의중앙선 환승" },
    { tag: "버스", icon: "🚌", title: "성동구청 정류장", desc: "도보 3분 · 간선 240, 410, 420 / 마을 성동08" },
    { tag: "셔틀", icon: "🚐", title: "주일 셔틀버스", desc: "왕십리역 / 마장동 / 성수동 3개 노선 운행 (8:30 / 10:30)" },
  ],
  verseOfWeek: {
    text: "주의 말씀은 내 발에 등이요\n내 길에 빛이니이다",
    ref: "시편 119:105",
  },
  calendar: {
    year: 2026,
    month: 4,
    today: 7,
    eventDays: [5, 8, 12, 19, 22, 26],
  },
  footerNav: {
    예배: ["주일예배", "수요예배", "새벽기도회", "금요철야"],
    참여: ["새가족 등록", "교회학교", "소그룹", "선교"],
    정보: ["공지사항", "설교 영상", "갤러리", "찾아오시는 길"],
  },
};
